export const ROLES = {
  SUPER_ADMIN: 'Super Admin',
  ADMIN: 'Admin',
  TREASURER: 'Treasurer',
  EVENT_MANAGER: 'Event Manager',
  VOLUNTEER: 'Volunteer',
  MEMBER: 'Member',
};

export const ROLE_KEYS = {
  SUPER_ADMIN: 'super_admin',
  ADMIN: 'admin',
  TREASURER: 'treasurer',
  EVENT_MANAGER: 'event_manager',
  VOLUNTEER: 'volunteer',
  MEMBER: 'member',
};

export const ROLE_DASHBOARD_ROUTES = {
  [ROLES.SUPER_ADMIN]: '/super-admin/dashboard',
  [ROLES.ADMIN]: '/admin/dashboard',
  [ROLES.TREASURER]: '/treasurer/dashboard',
  [ROLES.EVENT_MANAGER]: '/event-manager/dashboard',
  [ROLES.VOLUNTEER]: '/volunteer/dashboard',
  [ROLES.MEMBER]: '/member/dashboard',
  super_admin: '/super-admin/dashboard',
  admin: '/admin/dashboard',
  treasurer: '/treasurer/dashboard',
  event_manager: '/event-manager/dashboard',
  volunteer: '/volunteer/dashboard',
  member: '/member/dashboard',
};

export const DEMO_USERS = [
  {
    role: ROLES.SUPER_ADMIN,
    roleKey: ROLE_KEYS.SUPER_ADMIN,
    name: 'Dr. Eleanor Wright',
    title: 'Dean of Student Affairs & Super Admin',
    email: 'superadmin@campusflow.edu',
    studentId: 'FAC-88019',
    department: 'University Administration',
    year: 'Executive Faculty',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=256',
    route: '/super-admin/dashboard',
    badgeColor: 'danger',
    description: 'Full organizational authority, system configuration, all modules',
  },
  {
    role: ROLES.ADMIN,
    roleKey: ROLE_KEYS.ADMIN,
    name: 'Alex Rivera',
    title: 'Student Body President',
    email: 'admin@campusflow.edu',
    studentId: 'STU-94021',
    department: 'Computer Science & Business',
    year: 'Senior (Class of 2026)',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
    route: '/admin/dashboard',
    badgeColor: 'primary',
    description: 'Day-to-day operations, members, events, merchandise, announcements',
  },
  {
    role: ROLES.TREASURER,
    roleKey: ROLE_KEYS.TREASURER,
    name: 'Marcus Chen',
    title: 'Chief Financial Officer & Treasurer',
    email: 'treasurer@campusflow.edu',
    studentId: 'STU-94033',
    department: 'Finance & Economics',
    year: 'Junior (Class of 2027)',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=256',
    route: '/treasurer/dashboard',
    badgeColor: 'success',
    description: 'Financial oversight, income, expenses, budget allocation, payments',
  },
  {
    role: ROLES.EVENT_MANAGER,
    roleKey: ROLE_KEYS.EVENT_MANAGER,
    name: 'Sophia Patel',
    title: 'Director of Events & Programming',
    email: 'eventmanager@campusflow.edu',
    studentId: 'STU-94112',
    department: 'Media & Communications',
    year: 'Senior (Class of 2026)',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=256',
    route: '/event-manager/dashboard',
    badgeColor: 'info',
    description: 'Event production, ticket sales, venue capacity, attendance rosters',
  },
  {
    role: ROLES.VOLUNTEER,
    roleKey: ROLE_KEYS.VOLUNTEER,
    name: 'Aisha Al-Mansoor',
    title: 'Lead Campus Ambassador & Volunteer',
    email: 'volunteer@campusflow.edu',
    studentId: 'STU-95331',
    department: 'Data Science & Society',
    year: 'Sophomore (Class of 2028)',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
    route: '/volunteer/dashboard',
    badgeColor: 'warning',
    description: 'Assigned committee tasks, shift schedules, event check-in assistance',
  },
  {
    role: ROLES.MEMBER,
    roleKey: ROLE_KEYS.MEMBER,
    name: 'Elena Vance',
    title: 'Active Association Member',
    email: 'member@campusflow.edu',
    studentId: 'STU-95104',
    department: 'Biochemistry & Pre-Med',
    year: 'Freshman (Class of 2029)',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=256',
    route: '/member/dashboard',
    badgeColor: 'secondary',
    description: 'Membership pass, tickets, store orders, public announcements',
  },
];

export const getRouteForRole = (role) => {
  if (!role) return '/super-admin/dashboard';
  return ROLE_DASHBOARD_ROUTES[role] || '/super-admin/dashboard';
};
